### ISSUE TITLE
Fuel tanks store too little fuel

### ISSUE THREAD

**Issue by Monniasza** [net-lisias-ksp/ImpossibleInnovations#4]
I have noticed that tanks store too little fuel when testing my new SSTO spaceplane with TDRCS thrusters. The thrusters worked for only about 16 seconds, then I had no control and the spaceplane spun uncotrollably. After checking tanks, they were empty. After calculating mass of tritium it was only 300 grams.
The total mass of deuterium in largest tank is about 700 grams, but empty tank weighs 800kg, or 1142 times more.

I think that tanks should store about 10'000 times more fuel.

**Comment by Lisias** [comment]
Nope. This is working as intended on my (moderately) modded KSP instalment.

There's something wrong on your rig, I switching this from Feature Request to Support Request.

Please send your KSP.log, Player.log, ModuleManager.ConfigCache and everything on <KSP>/Logs so I can inspect it.

![](https://user-images.githubusercontent.com/64334/76710006-60268280-66e2-11ea-9089-fb9623349c57.png)

**Comment by Monniasza** [comment]
My modlist: [modlist.zip](https://github.com/net-lisias-ksp/ImpossibleInnovations/files/4336915/modlist.zip)

I'm using CKAN to install most mods, but here is custom-made mod: 
[SSTO Project.zip](https://github.com/net-lisias-ksp/ImpossibleInnovations/files/4336837/SSTO.Project.zip)

[KSP.log](https://github.com/net-lisias-ksp/ImpossibleInnovations/files/4336920/KSP.log)
[MiniAVC.log](https://github.com/net-lisias-ksp/ImpossibleInnovations/files/4336922/MiniAVC.log)
[Logs.zip](https://github.com/net-lisias-ksp/ImpossibleInnovations/files/4336924/Logs.zip)

**Comment by Lisias** [comment]
Urgh... I completely forgot about this one. Sorry. :(
